name: Check for broken links

on:
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out deezertidal.github.io repository
        uses: actions/checkout@v3
        with:
          repository: deezertidal/deezertidal.github.io
          path: deezertidal.github.io

      - name: Check for broken links
        id: lychee
        uses: lycheeverse/lychee-action@v1.0.9
        with:
          args: --output /tmp/lychee/out.md --verbose --no-progress --exclude 'deezertidal.github.io/.git' 'deezertidal.github.io/**'

      - name: Save report to GITHUB_STATE
        run: echo "report=${{ steps.lychee.outputs.report }}" >> $GITHUB_STATE

      - name: Check out freevpn repository
        uses: actions/checkout@v3
        with:
          path: freevpn

      - name: Save report to freevpn repository
        run: |
          echo "${{ env.report }}" > freevpn/broken-links-report.txt
          cd freevpn
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add broken-links-report.txt
          git commit -m "Update broken links report"
          git push 
