name: Check encoding
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0-16/4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: deezertidal/deezertidal.github.io
        token: ${{ secrets.PAT }}
    - name: Install Python and chardet
      run: sudo apt-get update && sudo apt-get install -y python3-pip && sudo pip3 install chardet
    - name: Check encoding of files
      run: |
        echo "$(date +'%m%d%y%H%M') ..." > report.txt
        for file in $(find . -type f \( -name "*.conf" -o -name "*.plugin" -o -name "*.module" -o -name "*.sgmodule" \)); do
          encoding=$(chardet -n $file | awk -F ': ' '{print $2}')
          if [ "$encoding" == "UTF-8" ]; then
            echo "$file is in UTF-8 encoding" >> report.txt
          else
            echo "$file is NOT in UTF-8 encoding" >> report.txt
          fi
        done
    - name: Upload report to repository
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: report.txt
    - name: Copy report to img folder in repository
      uses: actions/checkout@v3
      with:
        repository: deezertidal/freevpn
        token: ${{ secrets.PAT }}
        path: freevpn-repo
    - name: Copy report to img folder in repository
      run: |
        cp report.txt freevpn-repo/img/report.txt
        cd freevpn-repo
        git config user.name "ybnet.ga"
        git config user.email "actions@github.com"
        git add img/report.txt
        git commit -m "check files"
        git push origin main
